%%
%% Latvian translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-lv}
\LoadClass{boi2014}

%%
%% Strings
%%

\renewcommand{\Language}{LV}

\renewcommand{\Olympiad}{Baltijas Informātikas Olimpiāde}
\renewcommand{\OlympiadDay}{\DayNum . Diena}
\renewcommand{\LocationDate}{26.--30. Aprīlis, Palanga}

\renewcommand{\PageOf}[2]{Lapa #1 no #2}

\renewcommand{\TitleTask}{Uzdevums}
\renewcommand{\TitleImplementation}{Implementācija}
\renewcommand{\TitleOutput}{Izvaddati}
\renewcommand{\TitleInput}{Ievaddati}
\renewcommand{\TitleExample}{Piemērs}
\renewcommand{\TitleExamples}{Piemēri}
\renewcommand{\TitleScoring}{Vērtēšana}
\renewcommand{\TitleExplanation}{Komentāri}
\renewcommand{\TitleConstraints}{Ierobežojumi}
\renewcommand{\TitleExperimentation}{Eksperimentēšana}
