%%
%% Finnish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-fi}
\LoadClass{boi2014}

%%
%% Strings
%%

\renewcommand{\Language}{FI}

\renewcommand{\Olympiad}{Baltic Olympiad in Informatics}
\renewcommand{\OlympiadDay}{Päivä \DayNum}
\renewcommand{\LocationDate}{26.-30.4.2014, Palanga}

\renewcommand{\PageOf}[2]{Sivu #1/#2}

\renewcommand{\TitleTask}{Tehtävä}
\renewcommand{\TitleImplementation}{Toteutus}
\renewcommand{\TitleOutput}{Tuloste}
\renewcommand{\TitleInput}{Syöte}
\renewcommand{\TitleExample}{Esimerkki}
\renewcommand{\TitleExamples}{Esimerkit}
\renewcommand{\TitleScoring}{Pisteytys}
\renewcommand{\TitleExplanation}{Kommentit}
\renewcommand{\TitleConstraints}{Rajat}
\renewcommand{\TitleExperimentation}{Kokeileminen}
