%%
%% Danish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-dk}
\LoadClass{boi2014}

%%
%% Strings
%%

\renewcommand{\Language}{DK}

\renewcommand{\Olympiad}{Baltic Olympiad in Informatics}
\renewcommand{\OlympiadDay}{Dag \DayNum}
\renewcommand{\LocationDate}{26.--30.~april, Palanga}

\renewcommand{\PageOf}[2]{Side #1 af #2}

\renewcommand{\TitleTask}{Opgave}
\renewcommand{\TitleImplementation}{Implementering}
\renewcommand{\TitleOutput}{Output}
\renewcommand{\TitleInput}{Input}
\renewcommand{\TitleExample}{Eksempel}
\renewcommand{\TitleExamples}{Eksempler}
\renewcommand{\TitleScoring}{Pointgivning}
\renewcommand{\TitleExplanation}{Kommentarer}
\renewcommand{\TitleConstraints}{Begrænsninger}
