%%
%% German translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-de}
\LoadClass{boi2014}

%%
%% Strings
%%

\newcommand{\Language}{EN}

\newcommand{\Olympiad}{Baltic Olympiad in Informatics}
\newcommand{\OlympiadDay}{Day \DayNum}
\newcommand{\LocationDate}{26.--30. April, Palanga}

\newcommand{\PageOf}[2]{Seite #1 von #2}

\newcommand{\TitleTask}{Aufgabe}
\newcommand{\TitleImplementation}{Implementierung}
\newcommand{\TitleOutput}{Ausgabe}
\newcommand{\TitleInput}{Eingabe}
\newcommand{\TitleExample}{Beispiel}
\newcommand{\TitleExamples}{Beispiele}
\newcommand{\TitleScoring}{Bewertung}
\newcommand{\TitleExplanation}{Anmerkungen}
\newcommand{\TitleConstraints}{Constraints}
