%%
%% Swedish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-se}
\LoadClass{boi2014}

%%
%% Strings
%%

\renewcommand{\Language}{SE}

\renewcommand{\Olympiad}{Baltic Olympiad in Informatics}
\renewcommand{\OlympiadDay}{Dag \DayNum}
\renewcommand{\LocationDate}{26--30 april, Palanga}

\renewcommand{\PageOf}[2]{Sida #1 av #2}

\renewcommand{\TitleTask}{Uppgift}
\renewcommand{\TitleImplementation}{Implementation}
\renewcommand{\TitleOutput}{Utdata}
\renewcommand{\TitleInput}{Indata}
\renewcommand{\TitleExample}{Exempel}
\renewcommand{\TitleExamples}{Exempel}
\renewcommand{\TitleScoring}{Poängsättning}
\renewcommand{\TitleExplanation}{Kommentarer}
\renewcommand{\TitleConstraints}{Begränsningar}
