%%
%% German translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-de}
\LoadClass{boi2014}

%%
%% Strings
%%

\renewcommand{\Language}{DE}

%\newcommand{\Olympiad}{Baltic Olympiad in Informatics}
\renewcommand{\OlympiadDay}{Tag \DayNum}
\renewcommand{\LocationDate}{26.--30. April, Palanga}

\renewcommand{\PageOf}[2]{Seite #1 von #2}

\renewcommand{\TitleTask}{Aufgabe}
\renewcommand{\TitleImplementation}{Implementierung}
\renewcommand{\TitleOutput}{Ausgabe}
\renewcommand{\TitleInput}{Eingabe}
\renewcommand{\TitleExample}{Beispiel}
\renewcommand{\TitleExamples}{Beispiele}
\renewcommand{\TitleScoring}{Bewertung}
\renewcommand{\TitleExplanation}{Anmerkungen}
\renewcommand{\TitleConstraints}{Constraints}
\renewcommand{\TitleExperimentation}{Experimentieren}
