%%
%% Polish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-pl}
\LoadClass{boi2014}

\usepackage{polski}
\usepackage[polish]{babel}

%%
%% Strings
%%

\renewcommand{\Language}{PL}

\renewcommand{\Olympiad}{Bałtycka Olimpiada Informatyczna}
\renewcommand{\OlympiadDay}{Dzień \DayNum}
\renewcommand{\LocationDate}{26--30 kwietnia, Palanga}

\renewcommand{\PageOf}[2]{Strona #1 z #2}

\renewcommand{\TitleTask}{Zadanie}
\renewcommand{\TitleImplementation}{Implementacja}
\renewcommand{\TitleOutput}{Wyjście}
\renewcommand{\TitleInput}{Wejście}
\renewcommand{\TitleExample}{Przykład}
\renewcommand{\TitleExamples}{Przykłady}
\renewcommand{\TitleScoring}{Ocenianie}
\renewcommand{\TitleExplanation}{Komentarz}
\renewcommand{\TitleConstraints}{Ograniczenia}
