%%
%% Polish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-pl}
\LoadClass{boi2014}

%%
%% Strings
%%

\newcommand{\Language}{PL}

\newcommand{\Olympiad}{Bałtycka Olimpiada Informatyczna}
\newcommand{\OlympiadDay}{Dzień \DayNum}
\newcommand{\LocationDate}{26--30 kwietnia, Palanga}

\newcommand{\PageOf}[2]{Strona #1 z #2}

\newcommand{\TitleTask}{Zadanie}
\newcommand{\TitleImplementation}{Implementacja}
\newcommand{\TitleOutput}{Wyjście}
\newcommand{\TitleInput}{Wejście}
\newcommand{\TitleExample}{Przykład}
\newcommand{\TitleExamples}{Przykłady}
\newcommand{\TitleScoring}{Ocenianie}
\newcommand{\TitleExplanation}{Komentarz}
\newcommand{\TitleConstraints}{Ograniczenia}
