%%
%% Finnish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-fi}
\LoadClass{boi2014}

%%
%% Strings
%%

\renewcommand{\Language}{EN}

\renewcommand{\Olympiad}{Baltic Olympiad in Informatics}
\renewcommand{\OlympiadDay}{Day \DayNum}
\renewcommand{\LocationDate}{April 26--30, Palanga}

\renewcommand{\PageOf}[2]{Page #1 of #2}

\renewcommand{\TitleTask}{Task}
\renewcommand{\TitleImplementation}{Implementation}
\renewcommand{\TitleOutput}{Output}
\renewcommand{\TitleInput}{Input}
\renewcommand{\TitleExample}{Example}
\renewcommand{\TitleExamples}{Examples}
\renewcommand{\TitleScoring}{Scoring}
\renewcommand{\TitleExplanation}{Comments}
\renewcommand{\TitleConstraints}{Constraints}
