%%
%% Estonian translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-ee}
\LoadClass{boi2014}

\RequirePackage[estonian]{babel}
\RequirePackage[utf8]{inputenc}

%%
%% Strings
%%

\newcommand{\Language}{ET}

\newcommand{\Olympiad}{Baltic Olympiad in Informatics}
\newcommand{\OlympiadDay}{Day \DayNum}
\newcommand{\LocationDate}{April 26--30, Palanga}

\newcommand{\PageOf}[2]{#1 / #2}

\newcommand{\TitleTask}{Ülesanne}
\newcommand{\TitleImplementation}{Realisatsioon}
\newcommand{\TitleOutput}{Väljund}
\newcommand{\TitleInput}{Sisend}
\newcommand{\TitleExample}{Näide}
\newcommand{\TitleExamples}{Näited}
\newcommand{\TitleScoring}{Hindamine}
\newcommand{\TitleExplanation}{Märkused}
\newcommand{\TitleConstraints}{Piirangud}
