%%
%% Estonian translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-et}
\LoadClass{boi2014}

\RequirePackage[estonian]{babel}
\RequirePackage{amssymb}

%%
%% Strings
%%

\renewcommand{\Language}{ET}

%\newcommand{\Olympiad}{Baltic Olympiad in Informatics}
%\newcommand{\OlympiadDay}{Day \DayNum}
%\newcommand{\LocationDate}{April 26--30, Palanga}

\renewcommand{\PageOf}[2]{#1 / #2}

\renewcommand{\TitleTask}{Ülesanne}
\renewcommand{\TitleImplementation}{Realisatsioon}
\renewcommand{\TitleOutput}{Väljund}
\renewcommand{\TitleInput}{Sisend}
\renewcommand{\TitleExample}{Näide}
\renewcommand{\TitleExamples}{Näited}
\renewcommand{\TitleScoring}{Hindamine}
\renewcommand{\TitleExplanation}{Märkused}
\renewcommand{\TitleConstraints}{Piirangud}
\renewcommand{\TitleExperimentation}{Katsetamine}

\renewcommand{\le}{\leqslant}
\renewcommand{\ge}{\geqslant}
