%%
%% Danish translations.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{boi2014-dk}
\LoadClass{boi2014}

%%
%% Strings
%%

\newcommand{\Language}{EN}

\newcommand{\Olympiad}{Baltic Olympiad in Informatics}
\newcommand{\OlympiadDay}{Day \DayNum}
\newcommand{\LocationDate}{April 26--30, Palanga}

\newcommand{\PageOf}[2]{Page #1 of #2}

\newcommand{\TitleTask}{Task}
\newcommand{\TitleImplementation}{Implementation}
\newcommand{\TitleOutput}{Output}
\newcommand{\TitleInput}{Input}
\newcommand{\TitleExample}{Example}
\newcommand{\TitleExamples}{Examples}
\newcommand{\TitleScoring}{Scoring}
\newcommand{\TitleExplanation}{Comments}
\newcommand{\TitleConstraints}{Constraints}
